AWSTemplateFormatVersion: '2010-09-09'
Description: account-balances webscraping lambda function.

Resources:
  AccountBalancesTransformLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: account-balances-transform
      Description: "runs a lambda for account-balances-transform"
      Runtime: python3.8
      Handler: account_balances_transform.lambda_function
      Timeout: 600
      Role: arn:aws:iam::537808241319:role/service-role/account_balances_scraper_role
      Code:
