AWSTemplateFormatVersion: '2010-09-09'
Description: account-balances webscraping template.

Parameters:
  Environment:
    Type: String
    Description: Select the appropriate environment
    AllowedValues:
      - dev
      - prod

Resources:
  AccountBalancesTransformLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub account-balances-transform-${Environment}
      Description: !Sub "runs a lambda for account-balances-transform in ${Environment} environment"
      Runtime: python3.8
      Handler: transform_lambda_function.lambda_handler
      Timeout: 600
      Role: arn:aws:iam::537808241319:role/service-role/account_balances_scraper_role
      Code:
        S3Bucket: lambda-cloudformation-sourcecode-bucket
        S3Key: "account-balances/transform_lambda_function.zip"
      Layers: 
        - "arn:aws:lambda:ap-southeast-2:770693421928:layer:Klayers-p38-pandas:8"
        - "arn:aws:lambda:ap-southeast-2:770693421928:layer:Klayers-p38-lxml:3"
      Environment:
        Variables: 
          SNS_ARN: !Ref "SNSTopicEmail"

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(40 7 ? * MON-FRI *)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "AccountBalancesTransformLambda"
              - "Arn"
          Id: "AccountBalancesTransformLambda"
          
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "AccountBalancesTransformLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
  
  SNSTopicEmail:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "bensharkey3@gmail.com"
          Protocol: "email"
